### ISSUE TITLE
Additional Attributes for Subject

### ISSUE THREAD

**Issue by wuf810** [ateska/ios-csr#6]
I need to generate a CSR with additional custom subject attributes such as 

`serialNumber = 2334434-e407-466a-83bf-defr44,telephoneNumber = \+440799777777 etc
`
so basically the csr when decoded end ups including these attributes as follows :

`SET {
  SEQUENCE {
    OBJECT IDENTIFIER telephoneNumber (2 5 4 20)
    PrintableString '+4441481895349'
    }
  }
SET {
  SEQUENCE {
    OBJECT IDENTIFIER serialNumber (2 5 4 5)
    PrintableString '433a9952-e407-466a-83bf-dcad55d8aa10'
    }
  }
`

How do I go about doing this? I see I can use the +(void)appendSubjectItem method but what should the "what" parameter value be for additional attributes?

i.e. for common name you have defined 

`static uint8_t OBJECT_commonName[5] = {0x06, 0x03, 0x55, 0x04, 0x03};`

Could you give me some advice please.

**Comment by wuf810** [comment]
Ok so I've discovered that additional subject keys have predefined offsets. I found a list [https://www.itu.int/ITU-T/formal-language/itu-t/x/x520/2012/SelectedAttributeTypes.html](url) but I'm sure there is an official link somewhere.

Knowing the offsets means it should be easy to extend the class to handle my other requirements.

**Comment by TMSantos** [comment]
hey @wuf810 you managed to figured this out ? I need to add UID attribute: https://www.rfc-editor.org/rfc/rfc4519#section-2.39

**Comment by TMSantos** [comment]
update: found an website that encodes it https://misc.daniel-marschall.de/asn.1/oid-converter/online.php
